### PR TITLE
Add LDAP example with LDAP properties configuration

### PR DESCRIPTION
**Pull request by nicolas-moteau**
This pull request add an LDAP example.
This example use the feature provided in a pull request to loopback-component-passport that allow to defined properties we want from ldap in user profile: https://github.com/strongloop/loopback-component-passport/pull/219

Signed-off-by: Nicolas Moteau nicolas.moteau@orange.com

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@loay please review, check with @raymondfeng before landing.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loay** [comment]
@nicolas-moteau Sorry I didn't see this notification. 
I will review it today.

**Comment by nicolas-moteau** [comment]
@loay I added a quick tutorial in the README.md

**Comment by nicolas-moteau** [comment]
@loay, PR strongloop/loopback-component-passport#219 has been merge. If it's OK for you, I would be nice to have the example part merged.

**Comment by loay** [comment]
@raymondfeng Can you please give it a quick look as well? Thanks.

**Comment by nicolas-moteau** [comment]
Squashed !

**Comment by loay** [comment]
Thank you for your contribution

**Pull request merged**
